# Generated by Django 6.0.1 on 2026-01-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('taille', models.FloatField(help_text='Taille en mètres')),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dragons_photos/')),
            ],
        ),
    ]
