# Generated by Django 6.0.1 on 2026-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='couleur',
            field=models.CharField(choices=[('Rouge', 'Rouge'), ('Vert', 'Vert'), ('Bleu', 'Bleu'), ('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Or', 'Or'), ('Argent', 'Argent')], max_length=100),
        ),
    ]
